import { createHmac, randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { chmod, mkdir, writeFile } from "node:fs/promises";

const CONFIG_DIR = "/config";
const ENV_FILE = `${CONFIG_DIR}/.env.generated`;
const POSTGREST_FILE = `${CONFIG_DIR}/postgrest.conf`;

await mkdir(CONFIG_DIR, { recursive: true });

if (existsSync(ENV_FILE)) {
  console.log(`[init] Secrets already exist at ${ENV_FILE} - skipping generation.`);
  process.exit(0);
}

console.log("[init] First boot detected. Generating secrets...");

const POSTGRES_PASSWORD = randomBytes(24).toString("hex");
const JWT_SECRET = randomBytes(32).toString("hex");
const ADMIN_USER = "admin";
const ADMIN_PASS = generateAdminPassword();

const SUPABASE_ANON_KEY = makeJwt(
  '{"role":"anon","iss":"supabase","iat":1700000000,"exp":2000000000}',
  JWT_SECRET
);
const SUPABASE_SERVICE_KEY = makeJwt(
  '{"role":"service_role","iss":"supabase","iat":1700000000,"exp":2000000000}',
  JWT_SECRET
);

const envFile = `# Auto-generated by init-secrets.mjs - do not edit manually.
# To regenerate, delete this file and restart the stack.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ADMIN_USER=${ADMIN_USER}
ADMIN_PASS=${ADMIN_PASS}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}

# Derived connection strings (used by various services)
DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/agent_os
STORAGE_DATABASE_URL=postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@db:5432/agent_os
GOTRUE_DB_DATABASE_URL=postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@db:5432/agent_os?sslmode=disable
GOTRUE_JWT_SECRET=${JWT_SECRET}
PGRST_DB_URI=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/agent_os
PGRST_JWT_SECRET=${JWT_SECRET}
DB_PASSWORD=${POSTGRES_PASSWORD}
SECRET_KEY_BASE=${JWT_SECRET}
ANON_KEY=${SUPABASE_ANON_KEY}
SERVICE_KEY=${SUPABASE_SERVICE_KEY}
VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
`;

const postgrestConfig = `db-uri = "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/agent_os"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "${JWT_SECRET}"
`;

await writeFile(ENV_FILE, envFile, "utf8");
await chmod(ENV_FILE, 0o644);
await writeFile(POSTGREST_FILE, postgrestConfig, "utf8");
await chmod(POSTGREST_FILE, 0o644);

console.log("[init] Secrets generated successfully.");
console.log("");
console.log(`  ADMIN_USER: ${ADMIN_USER}`);
console.log(`  ADMIN_PASS: stored in ${ENV_FILE}`);
console.log("");
console.log("  Keep the generated config volume backed up.");
console.log("");
console.log(`  Generated config written to ${ENV_FILE}`);

function base64Url(value) {
  return Buffer.from(value)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

function generateAdminPassword() {
  let password = "";

  while (password.length < 20) {
    password += randomBytes(18)
      .toString("base64")
      .replace(/[=+/]/g, "");
  }

  return password.slice(0, 20);
}

function makeJwt(payload, secret) {
  const header = '{"alg":"HS256","typ":"JWT"}';
  const encodedHeader = base64Url(header);
  const encodedPayload = base64Url(payload);
  const signature = createHmac("sha256", secret)
    .update(`${encodedHeader}.${encodedPayload}`)
    .digest("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");

  return `${encodedHeader}.${encodedPayload}.${signature}`;
}
