#!/bin/sh
# Auto-generate all secrets on first boot.
# Writes to /config/.env.generated — sourced by all services.
# Also writes /config/postgrest.conf for PostgREST (no shell available).
# Only runs if the file doesn't already exist (idempotent).

set -eu

CONFIG_DIR="/config"
ENV_FILE="$CONFIG_DIR/.env.generated"

mkdir -p "$CONFIG_DIR"

if [ -f "$ENV_FILE" ]; then
  echo "[init] Secrets already exist at $ENV_FILE — skipping generation."
  exit 0
fi

echo "[init] First boot detected. Generating secrets..."

# Generate random values
POSTGRES_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 32)
ADMIN_USER="admin"
ADMIN_PASS=$(openssl rand -base64 16 | tr -d '=/+' | head -c 20)

# --- Derive Supabase keys from JWT_SECRET ---
b64url() {
  openssl base64 -A | tr '+/' '-_' | tr -d '='
}

make_jwt() {
  local payload="$1"
  local header='{"alg":"HS256","typ":"JWT"}'
  local h=$(echo -n "$header" | b64url)
  local p=$(echo -n "$payload" | b64url)
  local sig=$(echo -n "$h.$p" | openssl dgst -sha256 -hmac "$JWT_SECRET" -binary | b64url)
  echo "$h.$p.$sig"
}

SUPABASE_ANON_KEY=$(make_jwt '{"role":"anon","iss":"supabase","iat":1700000000,"exp":2000000000}')
SUPABASE_SERVICE_KEY=$(make_jwt '{"role":"service_role","iss":"supabase","iat":1700000000,"exp":2000000000}')

# Write env file — includes ALL derived connection strings so every service
# can simply source this file without additional computation.
cat > "$ENV_FILE" <<EOF
# Auto-generated by init-secrets.sh — do not edit manually.
# To regenerate, delete this file and restart the stack.
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ADMIN_USER=$ADMIN_USER
ADMIN_PASS=$ADMIN_PASS
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY

# Derived connection strings (used by various services)
DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/agent_os
STORAGE_DATABASE_URL=postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@db:5432/agent_os
GOTRUE_DB_DATABASE_URL=postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@db:5432/agent_os?sslmode=disable
GOTRUE_JWT_SECRET=$JWT_SECRET
PGRST_DB_URI=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/agent_os
PGRST_JWT_SECRET=$JWT_SECRET
DB_PASSWORD=$POSTGRES_PASSWORD
SECRET_KEY_BASE=$JWT_SECRET
ANON_KEY=$SUPABASE_ANON_KEY
SERVICE_KEY=$SUPABASE_SERVICE_KEY
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
EOF

chmod 644 "$ENV_FILE"

# Write PostgREST config file (PostgREST image has no shell, reads config from file)
cat > "$CONFIG_DIR/postgrest.conf" <<EOF
db-uri = "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/agent_os"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "${JWT_SECRET}"
EOF

chmod 644 "$CONFIG_DIR/postgrest.conf"

echo "[init] Secrets generated successfully."
echo ""
echo "  ADMIN_USER: $ADMIN_USER"
echo "  ADMIN_PASS: stored in $ENV_FILE"
echo ""
echo "  Keep the generated config volume backed up."
echo ""

echo "  Generated config written to $ENV_FILE"
